In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.
print(np.show_config())

blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Aida/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Aida/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Aida/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Aida/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Aida/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Aida/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Aida/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Aida/anaconda3\\Library\\in

In [3]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a=np.random.randint(6,size=(2,3,5))

#4. Print a.
print(a)

[[[5 1 1 5 1]
  [5 4 3 4 1]
  [5 5 4 0 2]]

 [[5 0 1 5 2]
  [2 5 3 3 1]
  [1 2 5 4 2]]]


In [4]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b=np.random.randint(2,size=(5,2,3)) #now we have a file with numbers from 0 to 1 and 5 dimensions of 2 rows and 3 columns each

In [5]:
#6. Print b.
print(b)

[[[0 1 1]
  [0 1 0]]

 [[0 1 1]
  [1 1 1]]

 [[1 0 1]
  [0 0 0]]

 [[1 1 1]
  [0 0 0]]

 [[0 1 0]
  [1 0 0]]]


In [7]:
#7. Do a and b have the same size? How do you prove that in Python code?
def lenx(var):
    x=len(var)
    return x

print(lenx(a))
print(lenx(b))

if lenx(a)==lenx(b):
    print("both arrays have the same size")
else:
    print("both arrays have different sizes")

2
5
both arrays have different sizes


In [8]:
#8. Are you able to add a and b? Why or why not?
c = np.add(a,b) #nope, I cannot sum them because the number of dimensions is different, the length is different, so I cannot match them


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [10]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c=np.transpose(b,(1,2,0)) #we are specifying that the order of transposition has to be 1,2,0 (element 1 in b has to be now element 0 in c and so on)
print(np.shape(c))
#now we get an array which is formed, like b, by numbers 0 and 1, but transposed: 2 dimensions of 3 rows and 5 columns (like a)

(2, 3, 5)


In [16]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d=c+a #now we can add them as they have the same shapes!
d

#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print(d)

[[[5 1 1 5 1]
  [5 4 3 4 1]
  [5 5 4 0 2]]

 [[5 0 1 5 2]
  [2 5 3 3 1]
  [1 2 5 4 2]]]
[[[5 1 2 6 1]
  [6 5 3 5 2]
  [6 6 5 1 2]]

 [[5 1 1 5 3]
  [3 6 3 3 1]
  [1 3 5 4 2]]]


In [17]:
#12. Multiply a and c. Assign the result to e.
e=a*c

In [18]:
#13. Does e equal to a? Why or why not?
equal_result = (e == a)
print("Equality Comparison Result:")
print(equal_result) #in the first row of the first dimension, the first 3 values are equal between arrays, that's why equal_result array returns "True". The other two are false because they are different between arrays (3 vs.0 and 4 vs.0)


Equality Comparison Result:
[[[False False  True  True False]
  [ True  True False  True  True]
  [ True  True  True  True False]]

 [[False  True False False  True]
  [ True  True False False False]
  [False  True False False False]]]


In [21]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)


print (f"maximum value in d array is {d_max}; lmin value is {d_min}; the average is {d_mean}")

maximum value in d array is 6; lmin value is 1; the average is 3.4


In [22]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f=np.empty((2,3,5))
f


array([[[9.11085261e-312, 9.11084421e-312, 0.00000000e+000,
         0.00000000e+000, 1.00000000e+000],
        [1.16097020e-028, 1.26104862e-076, 2.17051576e-028,
         5.14869415e-062, 1.04917183e-153],
        [5.23081515e-143, 2.12713048e+160, 1.77393635e+160,
         1.12895612e-042, 8.67783877e-067]],

       [[5.43786184e-143, 3.59751658e+252, 1.46901661e+179,
         8.37404147e+242, 4.31999013e-096],
        [4.82337723e+228, 1.81786403e+185, 1.42143332e+160,
         4.21989903e-090, 9.59367231e-071],
        [1.12983478e-042, 5.04621343e+180, 1.94918963e-153,
         1.14484251e+243, 2.59903827e-144]]])

In [ ]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""



In [23]:
for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = 25
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] = 75
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 50
            elif d[i][j][k] == d_min:
                f[i][j][k] =0
            elif d[i][j][k] == d_max:
                f[i][j][k] =100

In [24]:
print(d_max)
print(d_min)
print(d_mean)

6
1
3.4


In [27]:

"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""
f

array([[[ 75.,   0.,  25., 100.,   0.],
        [100.,  75.,  25.,  75.,  25.],
        [100., 100.,  75.,   0.,  25.]],

       [[ 75.,   0.,   0.,  75.,  25.],
        [ 25., 100.,  25.,  25.,   0.],
        [  0.,  25.,  75.,  75.,  25.]]])

In [28]:
d

array([[[5, 1, 2, 6, 1],
        [6, 5, 3, 5, 2],
        [6, 6, 5, 1, 2]],

       [[5, 1, 1, 5, 3],
        [3, 6, 3, 3, 1],
        [1, 3, 5, 4, 2]]])

In [29]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

'\n#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values \n("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:\narray([[[ \'D\',  \'D\',  \'D\',  \'B\',  \'D\'],\n        [ \'D\',  \'D\',  \'B\',  \'B\',  \'B\'],\n        [ \'D\',  \'B\',  \'D\',  \'D\',  \'D\']],\n\n       [[ \'B\',  \'B\',  \'B\',  \'B\',  \'E\'],\n        [ \'D\',  \'D\',  \'D\',  \'D\',  \'D\'],\n        [ \'B\',  \'D\',   \'A\',  \'D\', \'D\']]])\nAgain, you don\'t need Numpy in this question.\n'

In [32]:
empty_str=np.empty((2,3,5), dtype="str")
print(empty_str) #to check it is empty

for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                value = "A"
                empty_str[i][j][k] = value
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                value = "B"
                empty_str[i][j][k] = value
            elif d[i][j][k] == d_mean:
                value = "C"
                empty_str[i][j][k] = value
            elif d[i][j][k] == d_min:
                value = "D"
                empty_str[i][j][k] = value
            elif d[i][j][k] == d_max:
                value = "E"
                empty_str[i][j][k] = value

print(empty_str)

[[['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]

 [['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]]
[[['B' 'D' 'A' 'E' 'D']
  ['E' 'B' 'A' 'B' 'A']
  ['E' 'E' 'B' 'D' 'A']]

 [['B' 'D' 'D' 'B' 'A']
  ['A' 'E' 'A' 'A' 'D']
  ['D' 'A' 'B' 'B' 'A']]]


In [33]:
d

array([[[5, 1, 2, 6, 1],
        [6, 5, 3, 5, 2],
        [6, 6, 5, 1, 2]],

       [[5, 1, 1, 5, 3],
        [3, 6, 3, 3, 1],
        [1, 3, 5, 4, 2]]])